<a href="https://colab.research.google.com/github/Izhan-07/Deployment-of-ML-using-FLASK/blob/main/Deployment_of_Machine_Learning_model_using_Flask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

# Importing the dataset

In [ ]:
df = pd.read_csv('Housing.csv')

In [ ]:
df.shape

(545, 13)

In [ ]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [ ]:
df.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [ ]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
df.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [ ]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
pd.Series({col:df[col].unique() for col in df})

price               [13300000, 12250000, 12215000, 11410000, 10850...
area                [7420, 8960, 9960, 7500, 8580, 16200, 8100, 57...
bedrooms                                           [4, 3, 5, 2, 6, 1]
bathrooms                                                [2, 4, 1, 3]
stories                                                  [3, 4, 2, 1]
mainroad                                                    [yes, no]
guestroom                                                   [no, yes]
basement                                                    [no, yes]
hotwaterheating                                             [no, yes]
airconditioning                                             [yes, no]
parking                                                  [2, 3, 0, 1]
prefarea                                                    [yes, no]
furnishingstatus             [furnished, semi-furnished, unfurnished]
dtype: object

# Encoding Categorical data

In [ ]:
for i in range(len(df)):
  if df['mainroad'][i]=="yes":
    df['mainroad'][i] = 1
  elif df['mainroad'][i]=="no":
    df['mainroad'][i] = 0
  if df['guestroom'][i]=="yes":
    df['guestroom'][i] = 1
  elif df['guestroom'][i]=="no":
    df['guestroom'][i] = 0
  if df['basement'][i]=="yes":
    df['basement'][i] = 1
  elif df['basement'][i]=="no":
    df['basement'][i] = 0
  if df['hotwaterheating'][i]=="yes":
    df['hotwaterheating'][i] = 1
  elif df['hotwaterheating'][i]=="no":
    df['hotwaterheating'][i] = 0
  if df['airconditioning'][i]=="yes":
    df['airconditioning'][i] = 1
  elif df['airconditioning'][i]=="no":
    df['airconditioning'][i] = 0
  if df['prefarea'][i]=="yes":
    df['prefarea'][i] = 1
  elif df['prefarea'][i]=="no":
    df['prefarea'][i] = 0
  if df['furnishingstatus'][i]=="furnished":
    df['furnishingstatus'][i] = 2
  elif df['furnishingstatus'][i]=="semi-furnished":
    df['furnishingstatus'][i] = 1
  elif df['furnishingstatus'][i]=="unfurnished":
    df['furnishingstatus'][i] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d

In [ ]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3        1         0        0   
1  12250000  8960         4          4        4        1         0        0   
2  12250000  9960         3          2        2        1         0        1   
3  12215000  7500         4          2        2        1         0        1   
4  11410000  7420         4          1        2        1         1        1   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0               0               1        2        1                2  
1               0               1        3        0                2  
2               0               0        2        1                1  
3               0               1        3        1                2  
4               0               1        2        0                2

In [ ]:
pd.Series({col:df[col].unique() for col in df})

price               [13300000, 12250000, 12215000, 11410000, 10850...
area                [7420, 8960, 9960, 7500, 8580, 16200, 8100, 57...
bedrooms                                           [4, 3, 5, 2, 6, 1]
bathrooms                                                [2, 4, 1, 3]
stories                                                  [3, 4, 2, 1]
mainroad                                                       [1, 0]
guestroom                                                      [0, 1]
basement                                                       [0, 1]
hotwaterheating                                                [0, 1]
airconditioning                                                [1, 0]
parking                                                  [2, 3, 0, 1]
prefarea                                                       [1, 0]
furnishingstatus                                            [2, 1, 0]
dtype: object

## Splitting the data of dependent variable in Y and independent variable in X

In [ ]:
X = df.iloc[:,1:].values
y = df.iloc[:,0].values

In [ ]:
X

array([[7420, 4, 2, ..., 2, 1, 2],
       [8960, 4, 4, ..., 3, 0, 2],
       [9960, 3, 2, ..., 2, 1, 1],
       ...,
       [3620, 2, 1, ..., 0, 0, 0],
       [2910, 3, 1, ..., 0, 0, 2],
       [3850, 3, 1, ..., 0, 0, 0]], dtype=object)

In [ ]:
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440

# Splitting the dataset into Training set and Test set

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)

## Concatanation of two vertical vectors
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 4019080.7   4585000.  ]
 [ 6258021.77  6083000.  ]
 [ 4392719.13  4007500.  ]
 [ 7335082.22  6930000.  ]
 [ 2892857.57  2940000.  ]
 [ 7084655.58  6195000.  ]
 [ 3258634.74  3535000.  ]
 [ 3196499.16  2940000.  ]
 [ 3520106.01  3500000.  ]
 [ 8359610.29  7980000.  ]
 [ 6646926.36  6755000.  ]
 [ 3788844.63  3990000.  ]
 [ 3734072.96  3150000.  ]
 [ 4616010.41  3290000.  ]
 [ 3946124.94  4130000.  ]
 [ 2023177.47  2660000.  ]
 [ 3975554.49  4410000.  ]
 [ 3624716.97  3710000.  ]
 [ 3210282.74  3360000.  ]
 [ 4668411.38  4270000.  ]
 [ 5893719.66  5005000.  ]
 [ 6415683.84  5383000.  ]
 [ 4657036.56  6440000.  ]
 [ 2704096.11  1890000.  ]
 [ 5356909.86  6125000.  ]
 [ 5740682.57  5460000.  ]
 [ 5337586.48  5803000.  ]
 [ 5444859.97  4620000.  ]
 [ 5702144.57  5530000.  ]
 [ 5865872.3   5950000.  ]
 [ 3307327.31  4305000.  ]
 [ 6299491.03  3640000.  ]
 [ 7123479.96  5250000.  ]
 [ 2960326.87  3325000.  ]
 [ 4424323.19  3703000.  ]
 [ 5125081.86  4753000.  ]
 [ 4947693.93  9100000.  ]
 

In [ ]:
from sklearn import metrics
Accuracy = r2_score(y_test,y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy)
 
#print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

 Accuracy of the model is 65.78


In [ ]:
# model = LinearRegression()

In [ ]:
# model.fit(X_train, y_train)

In [ ]:
# y_pred = model.predict(X_test)

In [ ]:
# r2_score(y_test, y_pred)

In [ ]:
 regressor.predict([[7240,4,2,3,1,0,0,0,1,2,1,2]])

array([8175632.09])

* Day 7 attendence: https://docs.google.com/forms/d/e/1FAIpQLScq9NI9U_ziNf302qwYczYkehWoXA9GnuaaxWyjKVgjgunrwQ/viewform

* Jamboard: https://jamboard.google.com/d/1MW70bDTFm6rlrXACfjPnABlFD4NAu3D9_JgFxTIbTT8/edit?usp=sharing, https://jamboard.google.com/d/1Boc_TURt7M7ZMlbUWwhMJdw020ZlfHcej4L_clgSRrE/edit?usp=sharing

* Ice Cream Dataset: https://drive.google.com/file/d/1rS8dVV4QhyC6eQVqOuarrbmCpURodDJB/view?usp=sharing

* Project dataset: https://drive.google.com/file/d/1mGd1jwG1jExXmJpmGgDhUY9awevlopdD/view

* Project Submission Form: https://forms.gle/2y4fnH8bX2yzeLvC8